image: node:10-alpine

# specify the location of the Open API Specification files within your project
# and the filename of the specification that you would like to display by default
variables:
  DOCS_FOLDER: "docs"
  SPEC_TO_DISPLAY: "openapi.yaml"

# These folders are cached between builds
cache:
  paths:
    - ./node_modules

# publishes all files from the $DOCS_FOLDER together with the static version of SwaggerUI
# sets the specification file named in $SPEC_TO_DISPLAY to be displayed by default
pages:
  stage: deploy
  before_script:
    - npm install swagger-ui-dist@3.26.0
  script:
    - mkdir gen_docs
    - cp -rp node_modules/swagger-ui-dist/* gen_docs
    - cp -rp $DOCS_FOLDER/* gen_docs
    - sed -i "s#https://petstore\.swagger\.io/v2/swagger\.json#$SPEC_TO_DISPLAY#g" gen_docs/index.html
  artifacts:
    paths:
      - gen_docs
  only:
    - master
