apiVersion: v1
data:
  APP_SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
  USER_SECRET_KEY: xxxxxxxxxxxxxxxxx
kind: ConfigMap
metadata:
  labels:
    app: redi-run-app
    tier: api
  name: redi-run-app-config
  namespace: default
