apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redi-run-app
    tier: api
  name: redi-run-app
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redi-run-app
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redi-run-app
        tier: api
    spec:
      containers:
      - env:
        - name: APP_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: APP_SECRET_KEY
              name: redi-run-app-config
        - name: USER_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: USER_SECRET_KEY
              name: redi-run-app-config
        image: registry.gitlab.com/btbtravis/redi-run-app:0.0.1
        imagePullPolicy: IfNotPresent
        name: redi-run-app-api
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: redi-run-app-gitlab
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
