apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redi-run-app
    tier: api
  name: redi-run-app
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redi-run-app
      tier: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redi-run-app
        tier: api
    spec:
      containers:
      - name: redi-run-app-api
        env:
        - name: APP_SECRET_KEY
          value: xxxxxxxxxxxxxxxxxxxxxxxx
        - name: AUTH0_CLIENT_ID
          value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        image: registry.gitlab.com/btbtravis/redi-run-backend:x.x.x
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: redi-run-app-gitlab
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
