apiVersion: v1
kind: Service
metadata:
  labels:
    app: redi-run-app
    tier: api
  name: redi-run-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: redi-run-app
    tier: api
  sessionAffinity: None
  type: ClusterIP
